spring:
  application:
    name: platform

  datasource:
    url : jdbc:postgresql://localhost:5432/fixit_db
    username: postgres
    password: psql1234

  jpa:
    hibernate:
      ddl-auto:  update
    show-sql: true
    properties:
      hibernate :
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jwt:
    secret: AzuoRrtS7H5u4dJK/LKhODI7TXs9NfqX+SAN48EEcLo=